### ISSUE TITLE
Checkboxes really separated

### ISSUE THREAD

**Issue by xamionex** [RomeoCantCode/PSNorthstarWatcher#19]
![image](https://user-images.githubusercontent.com/57235791/151006664-91990535-c9fe-4ac6-aed3-89ed42570616.png)

**Comment by xamionex** [comment]
This could be you just planning to add all the riffs, Not sure, close if you want

**Comment by RomeoCantCode** [comment]
wanted the "start this server manually" to be a bit separated just stand out abit. floor is lava is just placeholder for all riff overrides thats why it has that space in between.
