### ISSUE TITLE
[REQ] Current Path Servers

### ISSUE THREAD

**Issue by xamionex** [RomeoCantCode/PSNorthstarWatcher#21]
- [ ] Instead of settings default to LocalAppdata\NorthstarServers maybe the current path?

![image](https://user-images.githubusercontent.com/57235791/151007308-f90c9c69-e065-4169-b6d6-9fbe799b3306.png)

**Comment by RomeoCantCode** [comment]
since it's intended for not so experienced users mby just put it on desktop by default 😄

**Comment by xamionex** [comment]
I was thinking same folder?

**Comment by xamionex** [comment]
Yeah thinking more of it maybe localappdata is better since you can store opts in there aswell as the servers, when the user changes/reinstalls nothing needs to be recreated
