### ISSUE TITLE
Add configurable delay between server starts

### ISSUE THREAD

**Issue by RomeoCantCode** [RomeoCantCode/PSNorthstarWatcher#31]
for slower machines. might render them useless for a couple of minutes if you start 10 servers at the same time.

**Comment by xamionex** [comment]
Just realized you said configurable, Might be harder to implement

**Comment by xamionex** [comment]
This needs tickrate to be fixed as well because I have no idea how the sliders work

**Comment by RomeoCantCode** [comment]
don't worry I'll add it! should be no problem / not time consuming at all
